#######################################
# PHP application Docker container
#######################################
app:
  build: .
  dockerfile: Dockerfile.development
  links:
    - mysql
  ports:
    - "8009:80"
    - "10225:22"
  volumes:
    - ./app/:/app/
    - /tmp/debug/:/tmp/debug/
    - ./:/docker/
  volumes_from:
    - storage
  # cap and privileged needed for slowlog
  cap_add:
    - SYS_PTRACE
  privileged: true
  env_file:
    - etc/environment.yml
    - etc/environment.development.yml

#######################################
# MySQL server
#######################################
mysql:
  build: docker/mysql
  dockerfile: MySQL-5.5
  ports:
    - 13396:3306
  volumes_from:
    - storage
  volumes:
    - /tmp/debug/:/tmp/debug/
  env_file:
    - etc/environment.yml
    - etc/environment.development.yml

#######################################
# Storage
#######################################
storage:
  build: docker/storage/
  volumes:
    - /storage
